apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: omdemo/matchfunction/simple1vs1
      ko:
        main: ./matchfunction/simple1vs1
        dependencies:
          paths: ["matchfunction/simple1vs1/*.go"]
    - image: omdemo/matchfunction/backfill3
      ko:
        main: ./matchfunction/backfill3
        dependencies:
          paths: ["matchfunction/backfill3/*.go"]
    - image: omdemo/testdirector
      ko:
        main: ./cmd/testdirector
        dependencies:
          paths: ["**/*.go"]
          ignore: ["tests/**/*.go"]
deploy:
  kubectl:
    defaultNamespace: open-match
manifests:
  rawYaml:
    - ./matchfunction/simple1vs1/simple1vs1.yaml
    - ./matchfunction/backfill3/backfill3.yaml
    # for load-testing cli
    # - ./cmd/testdirector/testdirector.yaml
portForward:
  - resourceType: Service
    resourceName: open-match-frontend
    namespace: open-match
    port: 50504
    localPort: 50504
  - resourceType: Service
    resourceName: open-match-backend
    namespace: open-match
    port: 50505
    localPort: 50505
