kind: Deployment
apiVersion: apps/v1
metadata:
  name: matchfunction-simple1vs1
  labels:
    component: matchfunction-simple1vs1
spec:
  replicas: 1
  selector:
    matchLabels:
      component: matchfunction-simple1vs1
  template:
    metadata:
      labels:
        component: matchfunction-simple1vs1
    spec:
      containers:
        - name: matchfunction-simple1vs1
          image: omdemo/matchfunction/simple1vs1
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50502
---
kind: Service
apiVersion: v1
metadata:
  name: matchfunction-simple1vs1
  labels:
    component: matchfunction-simple1vs1
spec:
  selector:
    component: matchfunction-simple1vs1
  clusterIP: None
  type: ClusterIP
---
