kind: Pod
apiVersion: v1
metadata:
  name: matchfunction
  namespace: default
  labels:
    component: matchfunction
spec:
  containers:
    - name: matchfunction
      image: omdemo/matchfunction:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: grpc
          containerPort: 50502
---
kind: Service
apiVersion: v1
metadata:
  name: matchfunction
  namespace: default
  labels:
    component: matchfunction
spec:
  selector:
    component: matchfunction
  clusterIP: None
  type: ClusterIP
---
